name: 2D_McDA_PSC
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.14
  - attr=2.5.2
  - blosc=1.21.6
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - bzip2=1.0.8
  - c-ares=1.34.6
  - ca-certificates=2025.11.12
  - cairo=1.18.4
  - certifi=2025.11.12
  - cftime=1.6.4
  - contourpy=1.3.3
  - cycler=0.12.1
  - cyrus-sasl=2.1.28
  - dbus=1.16.2
  - double-conversion=3.3.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.61.0
  - freetype=2.14.1
  - graphite2=1.3.14
  - harfbuzz=12.2.0
  - hdf4=4.2.15
  - hdf5=1.14.6
  - icu=75.1
  - keyutils=1.6.3
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lcms2=2.17
  - ld_impl_linux-64=2.45
  - lerc=4.0.0
  - libaec=1.1.4
  - libblas=3.11.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.11.0
  - libclang-cpp21.1=21.1.7
  - libclang13=21.1.7
  - libcups=2.3.3
  - libcurl=8.17.0
  - libdeflate=1.25
  - libdrm=2.4.125
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libev=4.33
  - libexpat=2.7.3
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libgl=1.7.0
  - libglib=2.86.2
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.2.0
  - libiconv=1.18
  - libjpeg-turbo=3.1.2
  - liblapack=3.11.0
  - libllvm21=21.1.7
  - liblzma=5.8.1
  - libmpdec=4.0.0
  - libnetcdf=4.9.3
  - libnghttp2=1.67.0
  - libntlm=1.8
  - libopenblas=0.3.30
  - libopengl=1.7.0
  - libpciaccess=0.18
  - libpng=1.6.53
  - libpq=18.1
  - libsqlite=3.51.1
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libtiff=4.7.1
  - libuuid=2.41.2
  - libvulkan-loader=1.4.328.1
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.13.1
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libxslt=1.1.43
  - libzip=1.11.2
  - libzlib=1.3.1
  - llvmlite=0.45.1
  - lz4-c=1.10.0
  - matplotlib=3.10.8
  - matplotlib-base=3.10.8
  - munkres=1.1.4
  - ncurses=6.5
  - netcdf4=1.7.3
  - numba=0.62.1
  - numpy=2.3.5
  - openjpeg=2.5.4
  - openldap=2.6.10
  - openssl=3.6.0
  - packaging=25.0
  - pandas=2.3.3
  - patsy=1.0.2
  - pcre2=10.46
  - pillow=12.0.0
  - pip=25.3
  - pixman=0.46.4
  - pthread-stubs=0.4
  - pyhdf=0.11.6
  - pyparsing=3.2.5
  - pyside6=6.9.3
  - python=3.13.11
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.13
  - pytz=2025.2
  - qhull=2020.2
  - qt6-main=6.9.3
  - readline=8.2
  - scipy=1.16.3
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - six=1.17.0
  - snappy=1.2.2
  - statsmodels=0.14.6
  - tk=8.6.13
  - tornado=6.5.2
  - tzdata=2025b
  - wayland=1.24.0
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.6
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.46
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.2
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - zlib=1.3.1
  - zlib-ng=2.3.2
  - zstd=1.5.7
  
